services:
  - type: web
    name: pension-website
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: MYSQL_DATABASE
        value: pension
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: ""
      - key: MYSQL_ROOT_PASSWORD
        value: ""
